version: "3.9"

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:5.0.0
    hostname: wazuh.manager
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      INDEXER_URL: https://wazuh.indexer:9200
      INDEXER_USERNAME: admin
      INDEXER_PASSWORD: SecretPassword
      FILEBEAT_SSL_VERIFICATION_MODE: full
      SSL_CERTIFICATE_AUTHORITIES: /etc/ssl/root-ca.pem
      SSL_CERTIFICATE: /etc/ssl/filebeat.pem
      SSL_KEY: /etc/ssl/filebeat.key
      API_USERNAME: wazuh-wui
      API_PASSWORD: MyS3cr37P450r.*-
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - wazuh_ssl_root_ca:/etc/ssl/root-ca.pem
      - wazuh_ssl_cert:/etc/ssl/filebeat.pem
      - wazuh_ssl_key:/etc/ssl/filebeat.key
      - wazuh_manager_config:/wazuh-config-mount/etc/ossec.conf

  wazuh.indexer:
    image: wazuh/wazuh-indexer:5.0.0
    hostname: wazuh.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh_indexer_data:/var/lib/wazuh-indexer
      - indexer_ssl_root_ca:/usr/share/wazuh-indexer/config/certs/root-ca.pem
      - indexer_ssl_key:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.key
      - indexer_ssl_cert:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem
      - indexer_admin_cert:/usr/share/wazuh-indexer/config/certs/admin.pem
      - indexer_admin_key:/usr/share/wazuh-indexer/config/certs/admin-key.pem
      - indexer_config:/usr/share/wazuh-indexer/config/opensearch.yml
      - indexer_internal_users:/usr/share/wazuh-indexer/config/opensearch-security/internal_users.yml

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:5.0.0
    hostname: wazuh.dashboard
    restart: always
    ports:
      - "443:5601"
    environment:
      INDEXER_USERNAME: admin
      INDEXER_PASSWORD: SecretPassword
      WAZUH_API_URL: https://wazuh.manager
      DASHBOARD_USERNAME: kibanaserver
      DASHBOARD_PASSWORD: kibanaserver
      API_USERNAME: wazuh-wui
      API_PASSWORD: MyS3cr37P450r.*-
    volumes:
      - dashboard_ssl_cert:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - dashboard_ssl_key:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - dashboard_ssl_root_ca:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - dashboard_config:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - dashboard_wazuh_config:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
      - wazuh_dashboard_config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh_dashboard_custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
    depends_on:
      - wazuh.indexer
      - wazuh.manager

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_active_response:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh_ssl_root_ca:
  wazuh_ssl_cert:
  wazuh_ssl_key:
  wazuh_manager_config:

  wazuh_indexer_data:
  indexer_ssl_root_ca:
  indexer_ssl_key:
  indexer_ssl_cert:
  indexer_admin_cert:
  indexer_admin_key:
  indexer_config:
  indexer_internal_users:

  dashboard_ssl_cert:
  dashboard_ssl_key:
  dashboard_ssl_root_ca:
  dashboard_config:
  dashboard_wazuh_config:
  wazuh_dashboard_config:
  wazuh_dashboard_custom:
